name: ishallopentoday-client
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Web
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2016 David Baynard
license: BSD3
github: dbaynard/ishallopentoday
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - IsHallOpenToday
  - IsHallOpenToday.Dispatcher
  - IsHallOpenToday.Store
  - IsHallOpenToday.View
  dependencies:
  - base >=4.7 && <5
  - aeson
  - basic-prelude
  - deepseq
  - ghcjs-base
  - ishallopentoday-common
  - lucid
  - react-flux
executables:
  ishallopentoday-node:
    main: Main.hs
    source-dirs: node
    ghc-options: -Wall
    dependencies:
    - base
    - ghcjs-base
    - ishallopentoday-client
  ishallopentoday-client:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
    - base
    - ghcjs-base
    - ishallopentoday-client
tests:
  client-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - QuickCheck
    - ishallopentoday-client
