resolver: lts-7.0
compiler: ghcjs-0.2.0.9007000_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9007000_ghc-8.0.1:
         url: "http://tolysz.org/ghcjs/ghc-8.0-2016-09-14-lts-7.0-9007000.tar.gz"
         sha1: e81dd1c00d8b04bc0569fbc4f3d691845c000317
extra-deps:
- react-flux-1.1.1
