flags: {}
extra-package-dbs: []
packages:
- '.'
resolver: ghc-7.10
extra-deps:
- MonadCatchIO-transformers-0.3.1.3
- attoparsec-enumerator-0.3.4
- blaze-builder-enumerator-0.2.1.0
- bytestring-builder-0.10.8.1.0
- bytestring-mmap-0.2.2
- enumerator-0.4.20
- hakyll-4.7.5.2
- lrucache-1.2.0.0
- monads-tf-0.1.0.3
- regex-posix-0.95.2
- snap-core-0.9.8.0
- snap-server-0.9.5.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1
