name: ishallopentoday-server
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Web
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2016 David Baynard
license: BSD3
github: dbaynard/ishallopentoday
library:
  source-dirs: src
  exposed-modules:
  - IsHallOpenToday
  dependencies:
  - base >=4.7 && <5
  - aeson
  - basic-prelude
  - ishallopentoday-common
  - lucid
  - servant-server
  - servant-lucid
  - wai
  - warp
executables:
  ishallopentoday-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: impl(ghcjs >= 0.2.1)
      ghc-options: -dedupe
    dependencies:
    - base
    - ishallopentoday-server
tests:
  server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: impl(ghcjs >= 0.2.1)
      ghc-options: -dedupe
    dependencies:
    - base
    - hspec
    - ishallopentoday-server
